### ISSUE TITLE
Should Patch have a diff method?

### ISSUE THREAD

**Issue by 2426021684** [reflex-frp/reflex#100]
Should Patch have a diff method? Should a new typeclass be created? Or is this function useless?
```haskell
class Patch p where
    ...
    diff :: PatchTarget p -> PatchTarget p -> Maybe p
```

**Comment by ryantrinkle** [comment]
It would be useful, but it shouldn't be mandatory for all Patch types.  Our main use for Patches currently is in situations where we can construct them more efficiently than by diffing - e.g., if we know we're adding one thing to a list.  So, it might be useful to have this as a separate typeclass.
