### ISSUE TITLE
Git tag missing for 0.4 (and most earlier versions)

### ISSUE THREAD

**Issue by andersk** [reflex-frp/reflex#129]
The only tag in this repo is 0.3. I believe the other tags should be at

2e38448bbbf3d0216aa0ca2d11f0b56b09838159 0.0.1
9ed658b846d093288190f836eeb3cf32ebe39318 0.1.0
d3f936bb5533a582d0ed2e3b7ab7af7e9e69193c 0.1.1
c108ea4406915ad461c7c03cb94be2b8084a091a 0.2
d0ffd2bd230090fa83092f2ebaae04662bf2af74 0.3.1
1db982f69c9a068de3fddc205c87a4f86231c235 0.3.2
cc62c11a6cde31412582758c236919d4bb766ada 0.4.0

**Comment by ryantrinkle** [comment]
Thanks!  By the way, do you have any trick to figuring those out?

**Comment by andersk** [comment]
Not really, I just used a Bash `for` loop to `git diff --shortstat` against every commit in the repo and picked out the smallest diff, using manual inspection with `gitk` to break ties.

**Comment by ryantrinkle** [comment]
That sounds like a good approach :)  I'll try to keep tags up to date in the future!
