### ISSUE TITLE
behaviour behaviour problems

### ISSUE THREAD

**Issue by lspitzner** [reflex-frp/reflex#135]
I have reduced some problem down to the following testcase, based on reflex HEAD and reflex-host HEAD. the four tests below (one of which is uncommented) highlight the problem. The first fires on either event (which is expected, but not desired). All three remaining cases _should_ (i think) behave the same, but they don't. 2 and 3 show the same "broken" behaviour, while 4 shows the expected behaviour.

(My goal is to have a Dynamic which holds values from one event but fires according only to another event. But 2/3/4 behaving differently seems to be the underlying fundamental issue.)

~~~~.hs
module Main where
-- brittany @ module --columns=100



import qualified Reflex as R
import qualified Reflex.Host.App as RH
import           Control.Monad (void, forever)
import           Control.Concurrent (threadDelay, forkIO)
import           Control.Monad.IO.Class (liftIO)

import           Lens.Micro ((<&>))



main :: IO ()
main = R.runSpiderHost $ RH.hostApp $ do

  (counterE, counterT) <- RH.newExternalEvent
  _                    <- RH.performPostBuild $ do
    void $ liftIO $ forkIO $ forever $ do
      _ <- counterT ()
      threadDelay 1000000

  counterDyn           <- R.count counterE

  (delayedE, delayedH) <- RH.newExternalEvent
  RH.performEvent_ $ R.updated counterDyn <&> \i -> liftIO $ void $ delayedH (i :: Int)

  _beh2 <- R.hold 0 delayedE

  -- ONE
  ---- works:               (produces 01,12,23,34,..    as expected)
  -- outDyn1 <- R.zipDynWith const <$> R.holdDyn 0 delayedE <*> R.holdDyn () counterE
  -- RH.performEvent_ $ R.updated outDyn1 <&> \x -> liftIO $ print x
  
  -- TWO
  ---- does not work:       (produces 0,0,0,0,0,0..    expected 0,1,2,3..)
  -- let outE = R.tag _beh2 counterE
  -- RH.performEvent_ $ outE <&> \x -> liftIO $ print x
  
  -- THREE
  ---- does not work either (produces 0,0,0,0,0,0..    expected 0,1,2,3,..)
  -- outDyn' <- R.foldDynM (\_ _ -> R.sample _beh2) 0 delayedE
  -- RH.performEvent_ $ R.updated outDyn' <&> \x -> liftIO $ print x

  -- FOUR
  ---- works:               (produces 0,1,2,3.. as expected)
  let outE = R.switch $ _beh2 <&> (<$ counterE)
  RH.performEvent_ $ outE <&> \x -> liftIO $ print x


  -- RH.performEvent_ $ counterE <&> \_ -> liftIO $ putStrLn "counterE"
  RH.performEvent_ $ delayedE <&> \i -> liftIO $ putStrLn $ "delayedE " ++ show i
~~~~

**Comment by ryantrinkle** [comment]
Notes so far:
TWO: occurs with ghcjs with -O1 or -O2, but not ghc-8.0.2 (any -O) or ghcjs -O0
THREE: occurs with ghcjs with -O1 or -O2, and ghc-8.0.2 with -O1 or -O2 and -threaded

**Comment by lspitzner** [comment]
also interesting is that running several simultaneously gives different results. e.g.

~~~~.hs
  -- TWO
  ---- does not work:       (produces 0,0,0,0,0,0..    expected 0,1,2,3..)
  let outE = R.tag _beh2 counterE
  RH.performEvent_ $ outE <&> \x -> liftIO $ putStrLn $ "TWO " ++ show x
  
  -- THREE
  ---- does not work either (produces 0,0,0,0,0,0..    expected 0,1,2,3,..)
  outDyn' <- R.foldDynM (\_ _ -> R.sample _beh2) 0 delayedE
  RH.performEvent_ $ R.updated outDyn' <&> \x -> liftIO $ putStrLn $ "THREE " ++ show x

  -- FOUR
  ---- works:               (produces 0,1,2,3.. as expected)
  let outE' = R.switch $ _beh2 <&> (<$ counterE)
  RH.performEvent_ $ outE' <&> \x -> liftIO $ putStrLn $ "FOUR " ++ show x
~~~~

gives correct output under all circumstances.

testing more combinations, i got the following results:

- if 4 is enabled, everything works
- otherwise, if 3 is enabled, 2/3 are broken
- otherwise (only 2) works

**Comment by ryantrinkle** [comment]
@lspitzner Just pushed what I think is a fix.  Would you mind trying it out? (if you grab latest reflex-platform, it should be cached).

**Comment by lspitzner** [comment]
yep, seems to work. only tested on 8.2.1.

Now that this underlying issue is resolved: Is there a recommended way of implementing the `holdDynTriggeredBy :: a -> Event a -> Event b -> m (Dynamic a)` combinator? (essentially holdDyn over 2/3/4 output event.) All i can think of involves two `hold(Dyn)`s which is not that pretty. Though I guess performance probably is as good as it could be (?)

~~~~.hs
holdDynTriggeredBy i e t = hold i e >>= \b -> holdDyn i (tag b t)
~~~~

**Comment by lspitzner** [comment]
and of course thanks for the quick fix!

**Comment by ryantrinkle** [comment]
@lspitzner Of course! Thanks for reporrting :)

**Comment by lspitzner** [comment]
no suggestion for `holdDynTriggeredBy`?

**Comment by ryantrinkle** [comment]
Oh whoops, missed that!

Your `holdDynTriggeredBy` doesn't look so bad to me.  I took a stab at implementing it as a single `accum` that keeps both pieces of state, but it ends up with slightly different semantics, in that *both* events must trigger the output `updated` event (or a `holdUniqDyn` would need to be used to avoid that).

One thing it did force me to consider was what should happen when both events fire at the same time.  In your implementation, that will result in the output `Dynamic` having the old value from the `hold`, while the `hold` gets the new value for next time.  If you want to have the new value in output instead, that can be accomplished by turning your `hold` into another `holdDyn` and using `tagPromptlyDyn` where you're currently using tag.  Here's the code for all-in-one-hold:

```haskell
import Control.Monad.Fix
import Data.Align
import Data.These
import Reflex

holdDynTriggeredBy :: (Reflex t, MonadHold t m, MonadFix m) => a -> Event t a -> Event t b -> m (Dynamic t a)
holdDynTriggeredBy i e t = do
  let f (oldShowing, oldPending) change = case change of
        This newPending -> (oldShowing, newPending)
        That _ -> (oldPending, oldPending)
        These newPending _ -> (newPending, newPending) -- Use (oldPending, newPending) for non-prompt output
  d <- accum f (i, i) $ align e t
  return $ fst <$> d
```

**Comment by lspitzner** [comment]
right, `holdDynTriggeredBy` matches the 1 case above. I considered `align` too when thinking of alternatives that might give the correct behaviour for 2/3. but i don't want the _both events trigger_ part. `tagPromptlyDyn` is a good hint, if i end up needing prompt switching (not sure).
thanks!
