### ISSUE TITLE
mapDynM

### ISSUE THREAD

**Issue by andrewthad** [reflex-frp/reflex#136]
It's kind of unfortunate that `mapDynM` is deprecated since there is no way to replicate its functionality without resorting to `unsafeDynamic`. If this was intentional, feel free to close this issue.

**Comment by ryantrinkle** [comment]
@andrewthad Sorry about that!  I don't recall precisely why I deprecated them, but I think I was incorrect to do so.

That being said, it's now possible to implement it [much more cleanly](https://github.com/reflex-frp/reflex/commit/c810e6a20310e1e681bd11511e59eaae393c68df#diff-7b94c553f4210fef892de032e9dc1af6R114)!

**Comment by andrewthad** [comment]
That is way cleaner. Thanks!

**Comment by andrewthad** [comment]
One more thought. To be more consistent with the types of `push` and `foldDynM`, you may want to use `PushM` in the type instead of `MonadSample m => m`.

**Comment by ryantrinkle** [comment]
It's actually used as both PushM *and* PullM here - PullM in the first argument to buildDynamic and PushM in the second.  One of those rare real-life use cases for higher-rank types :)

**Comment by andrewthad** [comment]
ah, I had forgotten about `PullM`.
