### ISSUE TITLE
Monoid/Semigroup instances for PostBuildT

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex#141]
where `<>` == `>>`. This is handy in same cases for abstractions and simply because the precedence of these operators is different.

**Comment by ryantrinkle** [comment]
Hmm, this isn't something I've seen in other monads.  E.g.:

```
Prelude Data.Semigroup> print 5 <> print 3

<interactive>:7:1: error:
    • No instance for (Semigroup (IO ())) arising from a use of ‘<>’
    • In the expression: print 5 <> print 3
      In an equation for ‘it’: it = print 5 <> print 3
```

I would hesitate to add a semigroup instance without understanding why IO doesn't have one.  Also, I don't think `>>` is quite right.  Shouldn't it be:

```haskell
a <> b = (<>) <$> a <*> b
```
?

**Comment by 3noch** [comment]
I got this idea from `lucid`: https://hackage.haskell.org/package/lucid-2.9.9/docs/Lucid.html#t:Html

I said `>>` because I imagined the instance would only work over `()` (although making it collapse via `<>` would work too I suppose).

In my mind `IO` exists *only* for effects. However, `Widget`/`PostBuildT` exist *also* for templating. The `Monoid` instance makes more sense in the context of templating. But I agree it does not make much sense for effects.

**Comment by ryantrinkle** [comment]
Oh, looks like instances for `Semigroup` and `Monoid` for IO have been added recently.  In that case, PR away :D

**Comment by ryantrinkle** [comment]
https://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Monoid.html#t:Monoid
https://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Semigroup.html#t:Semigroup

**Comment by 3noch** [comment]
Haha, if base can do it, so can we!

**Comment by 3noch** [comment]
Actually if ReaderT had them then we could just derive them. I'll submit an issue upstream, add them here with a note that once they're upstreamed we can just derive them.

**Comment by ryantrinkle** [comment]
@3noch Sounds like a plan; thanks!

**Comment by 3noch** [comment]
https://github.com/haskell/mtl/issues/48

**Comment by 3noch** [comment]
Any other monads I should address? `Dynamic` perhaps?

**Comment by ryantrinkle** [comment]
Isn't Dynamic already a Semigroup and Monoid?

**Comment by 3noch** [comment]
Oh right you are.

**Comment by 3noch** [comment]
For this to be practical, I'll also need to add the instances to `RequesterT` etc.
