### ISSUE TITLE
Rename MonadDynamicWriter to DynamicWriter

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex#146]
I think `MonadDynamicWriter` should be named `DynamicWriter` to be consistent with `EventWriter`.

**Comment by ryantrinkle** [comment]
Agreed.  The way to do this is by renaming it and then adding an alias
```haskell
type MonadDynamicWriter = DynamicWriter
```

**Comment by ali-abrar** [comment]
This is done
