### ISSUE TITLE
Cannot install reflex-0.5.0 via stack 1.6.3

### ISSUE THREAD

**Issue by xgrommx** [reflex-frp/reflex#148]
Hello! I have some problem with installing reflex-0.5.0 via stack 1.6.3. I got this message
```
The following package identifiers were not found in your indices: reflex-0.5.0
Possible candidates: reflex-0.2, reflex-0.4.0, reflex-0.0.1, reflex-0.3.2, reflex-0.3, reflex-0.1.1, reflex-0.1.0, reflex-0.3.1.
```
But with stack 1.5.1 it works correctly.

**Comment by ryantrinkle** [comment]
@xgrommx 0.5 is not on hackage/stackage - only on github, for now.  You should be able to point stack at the github repo, and I suspect that will work.
