### ISSUE TITLE
Overly-restrictive depends

### ISSUE THREAD

**Issue by ag-eitilt** [reflex-frp/reflex#149]
I get that most of the development is happening on 0.5, but until that is released, 0.4 is still the "current" version on Hackage, and should be maintained. In particular, the upper limits on some of the build-depends no longer accept the newest versions, and so are not compatible with GHC 8.2.1. Fixing that does require slightly more than updating the .cabal, but of the ones that don't, I was able to build (and have the test suite pass, though the latter doesn't seem exhaustive) using:

- base-4.9.1.0 (my system's not set up for 4.10)
- dependent-sum-0.4
- these-0.7.4
- template-haskell-2.11.1.0 (see following note)
- syb-0.4.4

Unfortunately, I wasn't fully able to bring things up to date as I had some trouble getting template-haskell >= 2.12 (required for ghc-8.2.1) together, and the version of haskell-src-meta that would support that (and the associated haskell-src-exts) do introduce build errors. Anyone with a better knowledge of the codebase and a less restictive package system able to estimate the work required?

**Comment by ag-eitilt** [comment]
Working on a patch for this myself, but the 0.4 release is just marked with a tag rather than a full branch -- 0.2 and 0.5 are the only ones that have the latter. Should I just base my pull request on the closest preceeding branch, or would it be possible to create a new branch there in the main repo?

**Comment by ryantrinkle** [comment]
Just created branch named "0.4".  Thanks for working on this!

**Comment by ag-eitilt** [comment]
No problem! Still have one more thing to check when I get home tonight, but the patch is nearly ready as far as I can tell.

**Comment by ag-eitilt** [comment]
Well, the problem I had was using a rather... interesting build environment. That PR should be ready now.

**Comment by ag-eitilt** [comment]
Patch has been merged and the new version uploaded to Hackage.

**Comment by ag-eitilt** [comment]
Looks like I forgot to bump the upper bound of base past the version I have, to the correct one for ghc-8.2.1; would it be possible to file a revision on Hackage to fix that to be "<4.11"? Sorry!

**Comment by dfordivam** [comment]
This should not be required as the 0.5 release is on its way
