### ISSUE TITLE
Implement all methods of Monoid/Semigroup for those instances

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex#156]
c.f. #142

**Comment by 3noch** [comment]
@ryantrinkle To continue the discussion: Since `ReaderT` and `StateT` do not already have instances of `Monoid` or `Semigroup` we'd have to effectively implement those in a way that is demonstrably faster than the default implementations used already. Do you think it's worth baking in implementations of that and benchmarking until we find the fastest one? It could vary a great deal between underlying monads and monoids.

**Comment by ryantrinkle** [comment]
Not sure, but I'd be very hesitant to add an instance that's potentially in conflict with the way future instances work.  I'm not sure if that would be possible with what you're suggesting, but if so maybe we should just hold off.

**Comment by 3noch** [comment]
Oh I certainly wouldn't implement instances for `ReaderT` and `StateT` directly. My point is that because we don't have those instances, we can't just lift them into `PostBuildT`, etc. We'd have to actually implement them and be sure that the implementations are faster than the defaults.

**Comment by 3noch** [comment]
For example: `mconcat` for `ReaderT` could be written

```mconcat = fmap mconcat . sequenceA``` 

but that's almost certainly slower in most cases than the default implementation of `mconcat` which folds with `mappend`. That is, unless the underlying monoid's `mconcat` is so much faster than the default `mconcat` that it pays for the intermediate list. At least for the instances in Reflex, I'm doubtful we'd ever be in that situation. There are better implementations of `mconcat`, but they have different tradeoffs.

**Comment by ryantrinkle** [comment]
Hmm, interesting.  My assumption was that the default instance could be extremely bad, e.g. with list, if it associates wrong.  However, perhaps that's not the right assumption.

**Comment by 3noch** [comment]
My implementations are identical to those for `IO` (which is also using default instance implementations for `mconcat`, `sconcat`, and `stimes`). Does that provide any comfort? :P

**Comment by ryantrinkle** [comment]
Yep!  Happy to go with it unless someone reports an issue.
