### ISSUE TITLE
rename `hold` to work with Dynamics?

### ISSUE THREAD

**Issue by sboosali** [reflex-frp/reflex#157]
i.e.

    -- Dynamic, not Behavior
    hold :: (Reflex t, MonadHold t m) 
            => a 
            -> Event t a 
            -> m (Dynamic t a)

    -- with "B" or some suffix 
    holdB :: (Reflex t, MonadHold t m) 
            => a 
            -> Event t a 
            -> m (Behavior t a)

Having the shorter and cleaner name, 
this signals that Dynamics should be used over Behaviors, "by default" or "when possible".

(More a proposal for discussion, than an actual proposal, since this is a very breaking change). 

I'm currently learning reflex, and this post:

https://qfpl.io/posts/reflex/basics/dynamics/

mentions that:

> The reflex and reflex-dom libraries aren’t prescriptive about how you structure your application, but the common advice is to ***pass Dynamics as far down as possible*** into the code that generates DOM. If you follow that advice then you can arrange things so that your code is doing the same changes to the DOM as the various virtual DOM libraries would, but skipping the need to diff and patch the various DOM trees.

and I've encountered the "use Dynamics as much as possible" a lot.

**Comment by 3noch** [comment]
I'm not sure the quoted advice means "Use Dynamics _instead of_ Behaviors whenever possible." Rather I think it means "Use Dynamics instead of _not using_ Dynamics whenever possible." That is, write functions like `buildPage :: Dynamic PersonName -> m ()` instead of `buildPage :: PersonName -> m ()`.

**Comment by ryantrinkle** [comment]
Behaviors should be preferred over Dynamics when possible, but usually in
reflex-dom, Behaviors' lack of push makes them less useful (since the DOM
is a push-driven API).

**Comment by sboosali** [comment]
okay, that makes sense, thanks. So definitely correctly named.
