### ISSUE TITLE
Inconsistent status of *Cheap functions

### ISSUE THREAD

**Issue by ag-eitilt** [reflex-frp/reflex#159]
I've started adding Haddock to the undocumented functions, and came across the *Cheap family at the end of `Class.hs`. I presume they aren't actually intended to be deprecated, and just got added to that section of the export list accidentally? Or should each of them get a deprecation pragma the same version they're released?

And on that, is a separate `tagCheap` necessary? The only difference it has from `tag` is that it uses `pushAlwaysCheap` instead, but the function it pushes is the same `sample`-lambda as in the latter. Unless there's some hidden caching in the `Behavior`, shouldn't they have the exact same semantics?

**Comment by madelinja** [comment]
> Unless there's some hidden caching in the Behavior, shouldn't they have the exact same semantics?

There is no caching on Behaviors but the cost of caching the `sample` might be higher than just recomputing it for each consumer of the tagged Event.

In any case, you're right that these functions shouldn't be under the deprecated header in the export list.

**Comment by ryantrinkle** [comment]
@ag-eitilt The *Cheap functions should always have identical semantics to the non-cheap versions; mostly, they just have different performance (in general: lower constant complexity, but potentially higher variable complexity, depending on how they're used).

**Comment by dfordivam** [comment]
@ag-eitilt I think @ryantrinkle answered your query. Closing this now.
