### ISSUE TITLE
What about lazy event?

### ISSUE THREAD

**Issue by MarisaKirisame** [reflex-frp/reflex#160]
So suppose I created an computationally expensive event with foldDyn (so it is inside a monadwidget), and pass it into some user defined function. Now there is a good chance that the user defined function will ignore it and do nothing.

So basically, a event is registered but never used.

Will it still be busy calculating? Or will it get optimized away?

**Comment by ryantrinkle** [comment]
It will calculate until it is eliminated by the garbage collector. The
reason is that, otherwise, it would miss input event occurrences that came
before the output was subscribed to. All functions that create state (i.e.
monadhold functions) work this way.

**Comment by MarisaKirisame** [comment]
When will it be eliminated though?

**Comment by ryantrinkle** [comment]
When the garbage collector runs, if there aren't any outstanding references to the state cell ('hold's), it will eliminate all the subscriptions from the events, which will stop the updating.  Unfortunately, GC isn't super predictable, although you can [trigger it manually](https://hackage.haskell.org/package/base-4.10.1.0/docs/System-Mem.html#v:performGC).

One other thing to note: I don't think foldDyn will actually *force* each value, so even though the folding will continue, it may not actually do the work of your combining function until something needs it.

**Comment by MarisaKirisame** [comment]
So let me repeat: foldDyn will eagerly push, but the value inside is still lazy, and is a thunk, so that expensive computation is not carry out.

Did I get it?
