### ISSUE TITLE
Suggestion: Have a list that show who is using reflex/reflex-dom

### ISSUE THREAD

**Issue by MarisaKirisame** [reflex-frp/reflex#161]
This way, it might attract more people to try reflex
It is good for users too, since we can look at other's code to learn, given that documentation is not very good (especially for reflex-dom)

**Comment by sboosali** [comment]
Yes, please! 

iirc, @ElvishJerricco, @mightybyte, and obviously @ryantrinkle have used it professionally, and I remember several other commenters mentioning reflex in production on r/haskell.

**Comment by Dridus** [comment]
we (Confer Health) also have it in prod

**Comment by MarisaKirisame** [comment]
The reflex community have been helping me a lot, so I can curate such a list myself, if the devs dont want to do it.

**Comment by alexfmpe** [comment]
What about doing this kinda like a list of reverse dependencies?
So, for this repo, something like
```
* reflex-frp
  * reflex-dom
  * reflex-sdl2
* some-org
  * some-opensource-repo-link
  * some-proprietary-project-name: some description
```
and in reflex-dom
```
* reflex-frp
  * reflex-dom-ui
* etc
  * etc
  * etc
```

**Comment by ryantrinkle** [comment]
That sounds useful :) perhaps we can use the reverse package tool that
exists somewhere already. It would also be useful to know about commercial
users

**Comment by alexfmpe** [comment]
Oh nice find
https://packdeps.haskellers.com/reverse/reflex

**Comment by alexfmpe** [comment]
> https://packdeps.haskellers.com/reverse/reflex

Some of these seem half-abandoned: no commits for over two years, builds failing, stuff like that.
Should we have some kind of criteria for listing things or just dump everything and then have some warnings/tags ?

**Comment by ryantrinkle** [comment]
We need to get our own house in order - i.e. make a reflex release - before
we do any of this, I think.

**Comment by alexfmpe** [comment]
As @ryantrinkle said, we won't be able to populate/curate a list ourselves right now, but feel free to get the ball rolling on that and/or continue the discussion. 

I made a [little template](https://github.com/alexfmpe/reflex/blob/e5b9777c75276399763dc9989ab8e86d777dc878/README.md#who-is-using-reflex) just to see how it would look but change anything you see fit.

It might make sense to add one-line descriptions to each entry. 
That and moving the list to its own file if it gets too big.

**Comment by alexfmpe** [comment]
To answer myself above: we don't have any rejection criteria as of now

**Comment by MarisaKirisame** [comment]
Neither Do I. I am planning to just make a table, include info like last commit, reflex version, github star (if applicable), build success (or not).
When the list grow I will think of ways to sort it and than reject, but I wont worry for now, since there are not that much peopple.

**Comment by ryantrinkle** [comment]
@MarisaKirisame Sounds awesome; thanks so much!

**Comment by gspia** [comment]
At the moment, most of the activity and open active projects are probably on github and it show's that there is about 180 projects, if [searching](https://github.com/search?l=Haskell&q=reflex&type=Repositories&utf8=%E2%9C%93).

Some of the once popular projects seem to be abandoned and there is redundancy (a lot of small do-something-to-learn-projects).

[Sorting](https://github.com/search?l=Haskell&o=desc&q=reflex&s=updated&type=Repositories&utf8=%E2%9C%93) shows projects that have been updated lately.

**Comment by mckeankylej** [comment]
cc @andrewthad

**Comment by andrewthad** [comment]
I currently use reflex and reflex-dom at work.

**Comment by dfordivam** [comment]
Lets add this to reflex-frp.org
Added an issue to track this. https://github.com/reflex-frp/reflex-frp.org/issues/43
