### ISSUE TITLE
Delayed update event never seems to fire

### ISSUE THREAD

**Issue by shaunren** [reflex-frp/reflex#179]
The event defined [here](https://github.com/shaunren/adarkhs/blob/f245f5547e5c42c04fe7c2b5c6e94933dd772082/src/Widgets.hs#L187), which is a delayed event of a Dynamic update, never appears to fire for some reason, while `updated isAvailable` itself is firing normally. I wonder why this is the case.

Thanks!

**Comment by ali-abrar** [comment]
Hi @shaunren. Looks like an interesting project. What happens if you `performEvent` and print when that event fires?

**Comment by ali-abrar** [comment]
Also, does removing the `delay` have any impact? I'd be a little surprised if it did.

**Comment by shaunren** [comment]
I changed `delay 0 ev` to `performEvent ev $ const $ return ()`, and it works now. It appears that the event created by `performEventAsync` is ignored when using EventWriter.

**Comment by ali-abrar** [comment]
I wasn't able to find in the code where the action was actually being
_performed_ in your original code. Could you point that out to me?

**Comment by shaunren** [comment]
It's performed [here](https://github.com/shaunren/adarkhs/blob/f245f5547e5c42c04fe7c2b5c6e94933dd772082/src/Main.hs#L177). `evUserActions` is the result from `runEventWriterT`.

**Comment by dfordivam** [comment]
@shaunren I used the `Event` created from `performEventAsync` with `tellEvent`, and it seems to work fine.

**Comment by ali-abrar** [comment]
@shaunren let us know if you run into any more trouble. good luck with the project!
