### ISSUE TITLE
Quickref implies Functor (Dynamic t) which is not in place for many years?

### ISSUE THREAD

**Issue by kindaro** [reflex-frp/reflex#187]
Maybe I am missing something, but I had [this problem][st] and it turns out the [official quickref][qu] is misleading in that it mentions `fmap :: (a -> b) -> Dynamic a -> Dynamic b` while in actuality one should use the monadic `mapDyn`.

[st]: https://stackoverflow.com/q/49813174
[qu]: https://github.com/reflex-frp/reflex/blob/develop/Quickref.md

**Comment by alexfmpe** [comment]
There's a [Functor instance](https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/Class.hs#L248) for Dynamic t, but it wasn't [always there](https://github.com/reflex-frp/reflex/commit/25b8921753f4eaa210c239694007ec30c93575f5#diff-2c23d73870bc5508a294d7d83a4ede40R121).

FWIW I managed to build and run your snippet directly inside `./try-reflex's` nix-shell by simply changing `String` to `Text`

I'm guessing the version or your .yml isn't recent enough?

**Comment by kindaro** [comment]
Your guess must be correct. I specified:
```
extra-deps:
- reflex-dom-0.3
```
— Chiefly because I know no better. I used the reference linked from the front page of the repo. I did have a suspicion that I should use another quickref.

Is there a recommended `stack.yaml` configuration for a smooth start?

[fp]: https://github.com/reflex-frp/reflex

**Comment by Lysxia** [comment]
That `Quickref.md` is on the `develop` branch, which is still unreleased. [`Quickref.md` for version 0.4.0.1](https://github.com/reflex-frp/reflex/blob/v0.4.0.1/Quickref.md) only references `mapDyn`.

**Comment by alexfmpe** [comment]
The recommended way is building via nix. See [project-development.md](https://github.com/reflex-frp/reflex-platform/blob/develop/docs/project-development.md).

You can also let a stack.yaml defer to nix by running it inside a nix-shell. 
For instance, your snippet can be built inside `./try-reflex` with `stack exec -- ghc myModule.hs` 
```
resolver: ghcjs-0.2.1_ghc-8.0.2
system-ghc: true
install-ghc: false

packages: []
```

Be sure to read the discussion in https://github.com/reflex-frp/reflex-platform/issues/116

**Comment by alexfmpe** [comment]
The recommended way is building via nix. See [project-development.md](https://github.com/reflex-frp/reflex-platform/blob/develop/docs/project-development.md).

You can also let a stack.yaml defer to nix by running it inside a nix-shell. 
For instance, your snippet can be built inside `./try-reflex` with `stack exec -- ghc myModule.hs` 
```
resolver: ghcjs-0.2.1_ghc-8.0.2
system-ghc: true
install-ghc: false

packages: []
```

Be sure to read the discussion in https://github.com/reflex-frp/reflex-platform/issues/116
