### ISSUE TITLE
any plan to support desktop?

### ISSUE THREAD

**Issue by MarisaKirisame** [reflex-frp/reflex#192]
So half a year ago, I try to build a structural editor using reflex-dom, but I find modeling line difficult, and the whole application is too slow. Since reflex is also supporting mobile, is there any plan to support desktop?

**Comment by ryantrinkle** [comment]
@MarisaKirisame If you build a reflex-dom app with ghc, it will produce a desktop app :)  Are there specific desktop app features that you need beyond what is currently provided?

**Comment by MarisaKirisame** [comment]
Wut? When is it added? I always thought reflex-dom is only for ghcjs!

I will try it and see how it goes.

**Comment by ryantrinkle** [comment]
@MarisaKirisame It's been there since original release :)

**Comment by ryantrinkle** [comment]
We should probably mention it more obviously!

**Comment by alexfmpe** [comment]
https://github.com/reflex-frp/reflex-platform/pull/308/

**Comment by MarisaKirisame** [comment]
This is amazing! I do nothing but change the build target, and everything work! And it is way faster than chrome!

How is this feat accomplished?

**Comment by MarisaKirisame** [comment]
It is still 5MB large though... jsfiddle or something alike?
