### ISSUE TITLE
Intended usage of MonadQuery/QueryT?

### ISSUE THREAD

**Issue by zarybnicky** [reflex-frp/reflex#198]
I've been staring at the code for quite some time, and I'm still not seeing it. I did manage to find some code using it in obsidiansystems/rhyolite and reflex-dom's websocket code, but I'm still not seeing how one should go about using the Query module...

It seems to me that it is extracted from rhyolite, given that there is a mention of `ViewSelector` in `Reflex.Query.Class`, which is not a thing in reflex or reflex-dom. `SelectedCount` then seems to be superfluous, unused in reflex at all.

Any hints? :)

**Comment by zarybnicky** [comment]
Also, when moving Query to reflex itself, why not move the Category instance as well? (https://github.com/obsidiansystems/rhyolite/blob/8922ee3147e3fb0fed1ebbd4db5bb01bca3bab42/common/Rhyolite/App.hs#L44)

**Comment by zarybnicky** [comment]
`runRhyoliteWidget` seems to be the closest to what I was looking for, but I still feel lost without seeing an instance of `HasView` (and View/ViewSelector)...

**Comment by ali-abrar** [comment]
Hi @zarybnicky - sorry for the delayed reply. QueryT can be used to request data from a datasource that is able to push responses to the the querying widget. For example, you might use QueryT to request certain data from your backend over a websocket (as is the case [here](https://github.com/reflex-frp/reflex-dom/blob/develop/reflex-dom-core/src/Reflex/Dom/WebSocket/Query.hs)) and then, as the backend determines that more/new data is relevant to your query, it could send additional updates in response to the original query. 

The type signature of `queryDyn` is probably a good starting point to understanding the intended use case:

`queryDyn :: (Reflex t, Monad m, MonadQuery t q m) => Dynamic t q -> m (Dynamic t (QueryResult q))`

Given a dynamically changing query, we're expecting to receive a dynamically changing query result. Note, however, that the result can change independently of the query.

Good suggestion, re: the category instance. Please let me know if you have any other questions.

Leaving this open as a reminder to add more documentation to QueryT.

**Comment by Ericson2314** [comment]
I recall from working on https://github.com/Ericson2314/matrix-client/blob/master/frontend/src/Frontend/Backend/QueryHandler.hs that https://github.com/reflex-frp/reflex-dom/blob/develop/reflex-dom-core/src/Reflex/Dom/WebSocket/Query.hs has some issues and/or some parts of it should probably be moved to reflex or at least separated from the websockets part.

Perhaps if we deduplicate this with the rhyolite stuff, the needed changes will just fall out of that.

**Comment by ali-abrar** [comment]
Documentation improved in #295

**Comment by zarybnicky** [comment]
@ali-abrar Thanks for the answer, even if it is more than half a year later. I'd had to pause my Reflex projects shortly after I opened this issue, but I'll be returning to them in a short while, so every little bit helps :)

Skimming through the docs, I'm only missing a short practical example (as with many other things in Reflex), but I'll try to play around with MonadQuery and post something if I get to a nice example.

I guess #295 combined with your answer above resolves my issue, closing for now.
