### ISSUE TITLE
Proposal: pushDyn primitive

### ISSUE THREAD

**Issue by Saulzar** [reflex-frp/reflex#213]
`pushDyn :: MonadHold t m => (a -> PushM t b) -> Dynamic t a -> m (Dynamic t b)`

I believe this would eliminate quite a few of the awkward situations where you would prefer to have a function with `Dynamic` input, but need the initial value. 

So currently you have two solutions (ignoring use of `sample` which is discouraged for good reason!)
1) Use `(a, Event t a)`
2) Use `postBuild` to sample the `Dynamic` later

I believe this eliminates the need for most of these awkward situations, would enable `factorDyn` without `sample` as well as simplify a lot of use of `postBuild`. It seems safe to me - implemented by a queue in Spider which gets processed similarly to the way `hold` is.

Happy to have a go at it when I get a few minutes too, just curious what people think first. Is there any reason it wouldn't work/be unsafe? @ryantrinkle?

**Comment by Saulzar** [comment]
Maybe the type should be something to do with `Incremental` instead of `Dynamic` though?

**Comment by Saulzar** [comment]
I realise this does not work for the same reason which `sample` can fail - if the `Dynamic` passed as input is a result of the `pushDyn` then it will fail even when deferred!

**Comment by ryantrinkle** [comment]
That's a really interesting idea! There is currently buildDynamic, which
has PullM but is otherwise the same as what you're proposing, I think. I
can't think of any reason offhand that it couldn't be changed to PushM.

**Comment by ryantrinkle** [comment]
That's a good point, and would definitely impact the (current) implementation.  We would need to keep running those callbacks to exhaustion, and we'd need to make sure to take into account anything else they might interleave with.  However, it all seems doable.

**Comment by Saulzar** [comment]
Well, it all compiles without changing much at all - I'll whip up some tests and see what's broken :)

**Comment by Saulzar** [comment]
Implemented with buildDynamic as discussed
