### ISSUE TITLE
Improve Reflex.Spider documentation

### ISSUE THREAD

**Issue by hololeap** [reflex-frp/reflex#219]
There doesn't seem to be much documentation for the `Reflex.Spider` module, such as its motivation or how to use it. All I see hinting to what it does is that "It uses a graph traversal algorithm to propagate Events and Behaviors", as mentioned in `Reflex.Spider.Internal`. Even the name `Spider` seems pretty mysterious: Is it referring to spiders in [this sense](https://en.wikipedia.org/wiki/Web_crawler) or [this sense](https://en.wikipedia.org/wiki/Spider), and what is the connection to FRP?

**Comment by dfordivam** [comment]
@hololeap `Reflex.Spider` is an implementation for `Reflex` class, and as is not directly useful for the users of reflex based libraries like `reflex-dom`. 

I guess you need to know about  `Reflex.Spider` code, only if you want to improve its performance or enhance it for some other use cases. 

In any case if you do go through the code internals and want to add documentation, then this is a good place to put it http://docs.reflex-frp.org/en/latest/reflex_docs.html#internals
