### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [reflex-frp/reflex#26]
Hi Ryan,

this is a standard request of mine with projects I use, or which I add to Debian:

Please consider adding your package to Stackage. Essentially, this gives you free QA and early feedback when something breaks, i.e. before your users notice. It does not require you to use Stackage or stack yourself. See http://www.stackage.org/authors for details.

Greetings,
Joachim

**Comment by ryantrinkle** [comment]
PR submitted: https://github.com/fpco/stackage/pull/796

**Comment by Cypher1** [comment]
Can this be reopened. I also use stack for my Haskell based work and as currently Nix OS isn't supported by Reflex. This leaves only try-reflex as a way to run / build code in reflex and I don't like that it takes over my command line (and breaks all my tab-completion/zsh features).

Thanks

**Comment by 3noch** [comment]
> currently Nix OS isn't supported by Reflex.

@Cypher1 I'm not sure what you mean by this. Do you mean that up-to-date `reflex` is not in `nixpkgs.haskellPackages`? Or that `stack` doesn't work on NixOS (without stack integration).

I actually use `stack` with its nix integration on NixOS (and macOS actually). It works quite well when used that way.

**Comment by Cypher1** [comment]
Hmm. Perhaps I've misunderstood this issue https://github.com/reflex-frp/reflex/issues/27

Is there a guide to setting up Nix & Stack somewhere, I've found a few repos with that setup but they are all horribly out of date and so no longer build on current stack installs.

**Comment by 3noch** [comment]
I have a goal to document this better, but here's what I have as an example:

You can create `default.nix` with `cabal2nix`.

## shell.nix
```nix
{ useGhc      ? true
, reflex-platform ? import ./reflex-platform {}
}:
let

  haskellPkgs = if useGhc then reflex-platform.ghc else reflex-platform.ghcjs;

  # Add development tools to the dependency tree
  # when working with GHC in the shell.
  devTools = if !useGhc then [] else [
    haskellPkgs.intero
    haskellPkgs.hlint_2_0_9
    haskellPkgs.project-m36
    haskellPkgs.stylish-haskell
    (pkgs.callPackage ./twitch-cli.nix {})
  ];

  drv = import ./default.nix { inherit common; };

  drvWithDevTools = pkgs.haskell.lib.overrideCabal drv (
    { buildDepends ? [], ...}: {
      buildDepends = buildDepends ++ devTools;
    }
  );

in reflex-platform.workOn haskellPkgs drvWithDevTools
```

## stack.nix
```yaml
nix:
  enable: true
  packages: []
  shell-file: shell.nix

resolver: ghc-8.0.2
system-ghc: true
packages:
  - '.'
```

**Comment by Cypher1** [comment]
Thanks! I'll try it out
