### ISSUE TITLE
Loosen `these` bounds to 0.7.7?

### ISSUE THREAD

**Issue by endgame** [reflex-frp/reflex#270]
Now that reflex-0.5 is on Hackage, nixpkgs master has it in hackage-packages.nix. Unfortunately, the version of `these` in nixpkgs is 0.7.6.

@luigy Recently tightened the upper bound for `these` from `< 0.8` to `< 0.7.6`. I'm having trouble driving the reflex build systems to actually test the relaxation. Is 0.7.6 safe for reflex, and if so, can someone please push a metadata rev to hackage?

**Comment by gwils** [comment]
It looks as though reflex 0.5 breaks with that version of `these`:

```
src/Reflex/Patch/MapWithMove.hs:173:51: error:
    Ambiguous occurrence ‘swap’
    It could refer to either ‘Data.These.swap’,
                             imported from ‘Data.These’ at src/Reflex/Patch/MapWithMove.hs:25:1-17
                          or ‘Data.Tuple.swap’,
                             imported from ‘Data.Tuple’ at src/Reflex/Patch/MapWithMove.hs:26:1-17
    |
173 |   where oldByValue = Map.fromListWith Set.union $ swap . first Set.singleton <$> Map.toList oldByIndex
    |                                                   ^^^^
```

so a new hackage release with a code change would be necessary to widen that bound.

**Comment by endgame** [comment]
Well, that's a shame, and an argument for explicit import lists.

**Comment by ElvishJerricco** [comment]
@endgame I just did `cabal new-repl -b reflex --allow-newer=reflex:these`.

**Comment by gwils** [comment]
```
cabal new-update
cabal get reflex
cd reflex-*
cabal new-build --allow-newer=these
```
