### ISSUE TITLE
Why is Dynamic not an instance of functor and applicative?

### ISSUE THREAD

**Issue by paldepind** [reflex-frp/reflex#28]
Hello

Reflex looks very interesting. I'd go as far as to say that it's among the most exciting things that has happened to FRP since Conals push and pull paper.

I was playing with the try-reflex tutorial. I attempted to modify a part of the tutorial program into this:

```haskell
nx <- numberInput
d <- dropdown "*" (constDyn ops) def
ny <- numberInput
op <- mapDyn stringToOp $ _dropdown_value d
result <- op <$> nx <*> ny
```

But it turns out that dynamic is not an instance of neither functor nor applicative? Why not? There is both `mapDyn` and `constDyn`?

**Comment by bennofs** [comment]
The problem is that `mapDyn` is monadic: it has type `MonadHold m => (a -> b) -> Dynamic t a -> m (Dynamic t b)`, not `(a -> b) -> Dynamic t a -> Dynamic t b`, as would be required for Functor.

Now, why is it monadic? Couldn't it just be implemented as `\f (Dynamic behavior event) -> Dynamic (fmap f behavior) (fmap f event)` ? The problem here is that in this implementation, `f` would be evaluated twice for the same value each time that the dynamic updates, since it's evaluated for the behavior and the event. To avoid this, `mapDyn` needs to use `hold` and this requires that it's monadic.

**Comment by paldepind** [comment]
> Now, why is it monadic? Couldn't it just be implemented as \f (Dynamic behavior event) -> Dynamic (fmap f behavior) (fmap f event) ? The problem here is that in this implementation, f would be evaluated twice for the same value each time that the dynamic updates, since it's evaluated for the behavior and the event. To avoid this, mapDyn needs to use hold and this requires that it's monadic. 

I don't understand this explanation. When implementing `map` you have a dynamic that allows notifications on changes and a function that takes these changes. It should be possible to return a new dynamic that contains the changes of the original passed through the function. Anyway, I am sure there are good reasons for this. I'll see if I can wrap my head around them.

Am I missing something or is neither Behaviour nor Event applicatives either?

Not implementing these standard type classes seems like a big trade of to me.

**Comment by ryantrinkle** [comment]
Behavior is a Functor/Applicative/Monad.  Event can't be an Applicative (you can't write 'pure'), but it is a functor.

With some additional work, we'll be able to make mapDyn pure without sacrificing any performance, at which point we'll be able to write Functor, Applicative, and Monad for Dynamic.

**Comment by paldepind** [comment]
> Event can't be an Applicative (you can't write 'pure'), but it is a Functor.

And this is due to the semantic differences between events in Reflex and events in classic FRP? The way Conal Elliot made his events applicatives seems quite nice.

> With some additional work, we'll be able to make mapDyn pure without sacrificing any performance, at which point we'll be able to write Functor, Applicative, and Monad for Dynamic.

That sounds great! :+1:

**Comment by ryantrinkle** [comment]
The approach of making `pure a` represent an Event that is always firing (with value `a`) isn't something I want to be able to represent.  In Reflex, you can rely on the fact that if a function doesn't receive an occurrence, it won't send one out; this is a rule that is extremely useful in practice.  However, any implementation of `pure` other than `const never` would violate this rule (and `const never` would violate the laws for Applicative).

**Comment by paldepind** [comment]
> In Reflex, you can rely on the fact that if a function doesn't receive an occurrence, it won't send one out; this is a rule that is extremely useful in practice. However, any implementation of pure other than const never would violate this rule (and const never would violate the laws for Applicative).

That sounds like a useful property. I don't understand how an always occurring event would break it though?

Also the way I understood Conal Elliots `pure a` it does not represent an event that is always occurring but instead an event that has always occurred. Because it occurs at -∞.

**Comment by ryantrinkle** [comment]
The trouble with those semantics is that they require keeping Event history around indefinitely.  This means that certain memory leaks are mandatory in the implementation.  Since my focus with Reflex was to produce an FRP system that could be used in production, I chose a semantics that allowed my implementation to rule out memory leaks definitively.  In Reflex, it's much easier to reason about the storage cost of Events: they only store at most one occurrence's value at a time, and only while that occurrence is propagating through the system.  After the frame is over, they go back to being empty - always.

**Comment by paldepind** [comment]
Ok. I understand. That sounds reasonable.

So is there no easy way to combine three dynamic values with a ternary function? To me the way this is done in the try-reflex example is quite awkward. I pair is being constructed with `combineDyn` just to be deconstructed again in another `combineDyn`.

```haskell
  nx <- numberInput
  d <- dropdown "*" (constDyn ops) def
  ny <- numberInput
  values <- combineDyn (,) nx ny
  result <- combineDyn (\o (x,y) -> stringToOp o <$> x <*> y) (_dropdown_value d) values
```

**Comment by mightybyte** [comment]
You can use qDyn.

    result <- $(qDyn [| func $(unqDyn [| nx |]) $(unqDyn [| ny |]) $(unqDyn [| _dropdown_value d |]) |])

I think Ryan also recently added a more convenient variant mkDyn that works like this.

    result <- $(mkDyn [| func $nx $ny $(_dropdown_value d) |])

**Comment by paldepind** [comment]
@mightybyte Thank you. I'll see if I can figure it out.

It looks like idiom brackets. Except they're not used on an applicative.

**Comment by mightybyte** [comment]
Yeah, it's better than applicative...it's any arbitrary expression.  And it's automatically optimized to be just as efficient as a single combineDyn.

**Comment by ryantrinkle** [comment]
Also, in the develop branch, there is an easier-to-use operator, mkDyn:

x <- [mkDyn| $a + $b + $c |]

It works the same as qDyn and unqDyn, but with much less syntactic overhead.

**Comment by paldepind** [comment]
Thanks to all of you for taking the time to answer my questions.

Where is the best place to answer questions? Here on GitHub, the subreddit or on irc?

**Comment by mightybyte** [comment]
I would recommend IRC.  This whole conversation could have happened in a few minutes on IRC instead of the week that it took here.

**Comment by 3noch** [comment]
But then I wouldn't have been able to read it as easily. ;)

**Comment by DiegoNolan** [comment]
Template Haskell seems like a ridiculous solution to this problem.

```
apDyn :: forall t m a b. (Reflex t, MonadHold t m)
      => m (Dynamic t (a -> b)) 
      -> Dynamic t a 
      -> m (Dynamic t b)
apDyn m a = do
  r <- m
  combineDyn (\f c -> f c) r a 
```
Why doesn't something like this exist?

**Comment by ryantrinkle** [comment]
@DiegoNolan That'll work just fine!  Many of the situations where I use `mkDyn` involve fairly deep expressions, so manually converting the whole thing to applicative style would be cumbersome.  Plus, some syntax, e.g. records, simply can't be preserved in applicative style.

If you'd like to send a PR adding that function, I'll be happy to merge it.

**Comment by DiegoNolan** [comment]
Can you provide some examples of the type of expressions you have in the QuasiQuoter? I'm wondering if I'm doing something wrong.

**Comment by ryantrinkle** [comment]
@DiegoNolan You're probably not doing anything wrong.  One situation is "spreadsheet-like" expressions, where you have a formula with a few Dynamic values scattered throughout, e.g. `[mkDyn| 1/2 * $a*$t^2 + $v*$t + $x0 |]`.  Basically, mkDyn is idiom braces specialized to Dynamics.

**Comment by ryantrinkle** [comment]
Hi everyone,

`Dynamic` is now an instance of `Functor`, `Applicative`, `Monad`, and several other classes; the old, monadic functions have been deprecated.

Thanks @paldepind for submitting the issue, @bennofs and @mightybyte for fielding questions, and @DiegoNolan for the great temporary workaround.

**Comment by jbaum98** [comment]
It seems to be no longer the case the Dynamic is an instance of Functor. What happened?

**Comment by ryantrinkle** [comment]
@jbaum98 It is the case, but it's been quite a while since we published to Hackage.  We've recently cut a release branch, and when that goes to Hackage it'll include the Functor instance.  Sorry for the wait!
