### ISSUE TITLE
How to convert `Event t JSVal` -> `Event t String`

### ISSUE THREAD

**Issue by cah6** [reflex-frp/reflex#314]
I have a framework that returns `Event t JSVal`, and I'm trying to figure out how to use use jsaddle's `valToJSON` to convert the event. I figure I can have something sort of like:
```
valToString :: MonadWidget t m => JSVal -> m String
valToString e = show <$> (liftJSM . valToJSON) e
```
but then if I apply that to my event like:
```
eJsVal <- ...
valToString <$> eJsVal
```
then I end up with `Event t (m String)` and not `m (Event t String)`, and it doesn't seem like I can `sequence` to reverse these layers. 

Is it possible to do something like this, either like this or some totally different way?

**Comment by tomsmalley** [comment]
`performEvent` might be what you are looking for

https://github.com/reflex-frp/reflex/blob/develop/Quickref.md#connecting-to-the-real-world-io

**Comment by cah6** [comment]
Thanks! I always saw that but wasn't sure exactly how to use it. For the curious that stumble on this:

Say you have a `eJSVal :: Event t JSVal`, and want to convert the JSVal to a JSON string, probably to print and play around with it before you do more rigorous parsing.

If you make a method like:
```
testJSM :: JSVal -> JSM String
testJSM eVal = do 
  json <- valToJSON eVal
  return $ unpack json
```
then you can call it like this (I did it from a method with constraint `MonadWidget t m`):
```
eJson <- performEvent $ (liftJSM . test) <$> eJSVal
```

Alternatively, you can push that liftJSM closer to the callsite that needs it, and make it so the method is a bit more general:
```
testMonadJSM :: MonadJSM m
  => JSVal
  -> m String
testMonadJSM eVal = do 
  json <- liftJSM $ valToJSON eVal
  return $ unpack json
```
which makes using it easier, since I assume `MonadJSM` has a `Performable` instance:
```
eJson <- performEvent (testMonadJSM <$> eJSVal)
```
