### ISSUE TITLE
Merge dependent-map upstream

### ISSUE THREAD

**Issue by saulzar** [reflex-frp/reflex#329]
Latest reflex develop depends on dependent-map > 0.3 which resides in an obscure branch:
https://github.com/obsidiansystems/dependent-map/tree/no-tag-classes

**Comment by Ericson2314** [comment]
You would want to start with releasing `dependent-sum` to hackage. See https://github.com/mokus0/dependent-sum/commit/290b45ffef1a845ca9f51609b4db47a93b9c20bc I scoped out another no-breaking `0.5.1` release before a breaking `0.6` release using `constraints-extras`. Of course `0.5.1` can be skipped, but then don't forget to modify the change log!

**Comment by cgibbard** [comment]
We should just get the whole thing out the door already.
