### ISSUE TITLE
Re-enable benchmarks in travis-ci builds

### ISSUE THREAD

**Issue by ali-abrar** [reflex-frp/reflex#338]
Currently disabled by a flag in `cabal.haskell-ci` because they take too long from a cold cache.

**Comment by saulzar** [comment]
Is it worth running benchmarks on a cloud service anyway? The numbers will have very high variation between runs (unpredictable system load)... most of the benchmarks are already running as tests.

**Comment by saulzar** [comment]
One intention is to create a/some benchmarks which are more typical and cover a representative set of operations (with the purpose of a quick sanity check). This would be better for the continuous integration

**Comment by ali-abrar** [comment]
Good point!
