### ISSUE TITLE
Reflex doesn't build with witherable-0.3.2

### ISSUE THREAD

**Issue by cdsmith** [reflex-frp/reflex#350]
witherable-0.3.2 now depends on monoidal-containers and defines a Filterable instance for MonoidalMap.  Unfortunately, so does reflex:Data.AppendMap.  As a result, reflex won't build with witherable-0.3.2.  Reflex should either (a) add an upper bound on witherable, (b) drop its local orphan instance and add a lower bound, or (c) all of the above using some CPP.

FYI @starsandspirals, this is the reason CodeWorld wasn't building for you earlier today.

**Comment by ali-abrar** [comment]
Unfortunately, it looks like this may be changing again soon: https://github.com/bgamari/monoidal-containers/issues/49

For now, I'll add an upper bound until monoidal-containers and witherable sort out where this instance ought to live.

**Comment by saulzar** [comment]
Is the min version macro not enough to deal with this?

#if !MIN_VERSION_witherable(0,3,2)
instance W.Filterable (MonoidalMap k) where
mapMaybe = mapMaybe

**Comment by saulzar** [comment]
I think perhaps that should have already fixed the issue. Phadej added it to fix the travis build and it seems like a more clean way around orphan instances which appear in multiple places..

But it's not on any Hackage release yet

**Comment by cdsmith** [comment]
Yes, it looks like that should fix it when the next Hackage release happens.

**Comment by ali-abrar** [comment]
> Is the min version macro not enough to deal with this?
> 
> #if !MIN_VERSION_witherable(0,3,2)
> instance W.Filterable (MonoidalMap k) where
> mapMaybe = mapMaybe

That is enough to fix it until a later version of witherable removes this instance. I think it might be better to just wait until the instance settles into its permanent home and until then stick with witherable < 0.3.2

**Comment by ali-abrar** [comment]
Fixed in version [0.6.2.3](http://hackage.haskell.org/package/reflex-0.6.2.3)
