### ISSUE TITLE
Metadata revision for reflex-0.6.1?

### ISSUE THREAD

**Issue by endgame** [reflex-frp/reflex#352]
`reflex-0.6.1` depends on `witherable >=0.2 && <0.4`. `witherable-0.3.2` added instances `Filterable (MonoidalMap k)` and `Witherable (MonoidalMap k)` which are provided as orphans in `reflex-0.6.1`.

**Comment by gwils** [comment]
As a hackage trustee, I have made a metadata revision tightening the upper bound from `< 0.4` to < 0.3.2` on reflex versions `0.6`, `0.6.1`, and `0.6.2.1`.

**Comment by ali-abrar** [comment]
@gwils Thank you!
