### ISSUE TITLE
Broken fallback code for `!MIN_VERSION_witherable(0,3,2)`?

### ISSUE THREAD

**Issue by endgame** [reflex-frp/reflex#353]
This line seems like it would infinite-loop instead of calling the `mapMaybe` from `Data.Map.Monoidal`:
https://github.com/reflex-frp/reflex/blob/5bba8405da85dc006de45ed5218f3d2d914c6057/src/Data/AppendMap.hs#L51

**Comment by saulzar** [comment]
Oh, yeah that looks really bad! Committed fix in #354

**Comment by endgame** [comment]
I'm not sure that's a fix. Don't you need to qualified-import `Data.Map.Monoidal` and then `MM.mapMaybe`?

**Comment by saulzar** [comment]
Yes, see follow up fix. Sorry!

**Comment by endgame** [comment]
Thanks a lot.
