### ISSUE TITLE
Use patch library in reflex

### ISSUE THREAD

**Issue by Ericson2314** [reflex-frp/reflex#381]
We pulled out the patch stuff in https://github.com/reflex-frp/patch/

1. Bump all cabal hashes in reflex platform.
2. Add `patch` to reflex platform.
3. Bump reflex platform in this repo, use patch, and reexport the modules under their old `Reflex.*` names.

**Comment by 3noch** [comment]
I don't see how this can be marked non-breaking unless we very consciously implement it to re-export everything?

**Comment by 3noch** [comment]
But without a PR it's hard to mark it either way.

**Comment by Ericson2314** [comment]
Yeah it should reexport the things for now. But pretty quickly we should *not* reexport it, and will also do some breaking changes on the `patch` side.
