### ISSUE TITLE
 combineDyn has an atipical signature

### ISSUE THREAD

**Issue by paolino** [reflex-frp/reflex#48]
combineDyn should be combineDynWith (,) 
If we follow the other funcWith standard wording.

**Comment by ryantrinkle** [comment]
I agree, but I question whether it's worth doing a deprecation cycle to improve consistency here.  `combineDyn` will also become a whole lot less relevant soon, when Functor (Dynamic t) is ready.

**Comment by cgibbard** [comment]
We may even just let it go away in favour of using general Applicative
stuff like liftA2 and liftA2 (,)

**Comment by ryantrinkle** [comment]
@paolino `combineDyn` has now been deprecated and replaced with [`zipDynWith`](https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/Class.hs#L637).  Thanks for pointing this out!
