### ISSUE TITLE
reflex only installs on 9.4.2 with --allow-new

### ISSUE THREAD

**Issue by GeorgeCo** [reflex-frp/reflex#482]
reflex only installs on 9.4.2 with --allow-new. 

It would be nice if it installed on 9.4.2 without the --allow-new option. Not sure if just fixing the version bound would be sufficient for using on 9.4.2

**Comment by danwdart** [comment]
Yes, I can't even get it to build at all as nix doJailbreak doesn't include core packages either.

**Comment by ali-abrar** [comment]
Should be fixed once https://github.com/reflex-frp/reflex/pull/486 is merged

**Comment by ali-abrar** [comment]
reflex-0.9 has been released, with support for ghc 9.4

**Comment by GeorgeCo** [comment]
Looks like the package bound has to increased for codeworld-api:


 cabal install codeworld-api --lib
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: base-4.17.0.0/installed-4.17.0.0 (user goal)
[__1] trying: codeworld-api-0.8.0 (user goal)
[__2] trying: hashable-1.4.2.0 (dependency of codeworld-api)
[__3] next goal: reflex (user goal)
[__3] rejecting: reflex-0.9.0.0 (conflict: codeworld-api => reflex>=0.6.3 &&
<0.9)
[__3] rejecting: reflex-0.8.2.2, reflex-0.8.2.1, reflex-0.8.2.0,
reflex-0.8.1.1, reflex-0.8.1.0, reflex-0.8.0.0, reflex-0.7.1.1,
reflex-0.7.1.0, reflex-0.7.0.0, reflex-0.6.4.1, reflex-0.6.4, reflex-0.6.3,
reflex-0.6.2.4, reflex-0.6.1, reflex-0.6, reflex-0.5.0.1, reflex-0.5,
reflex-0.4.0.1, reflex-0.4.0, reflex-0.3.2, reflex-0.3.1, reflex-0.3,
reflex-0.2, reflex-0.1.1, reflex-0.1.0, reflex-0.0.1, reflex-0.7.2.0,
reflex-0.6.2.3, reflex-0.6.2.1 (constraint from user target requires
==0.9.0.0)
