### ISSUE TITLE
0.4.0 on Hackage still has restrictive bounds for syb and haskell-src-exts

### ISSUE THREAD

**Issue by tejon** [reflex-frp/reflex#51]
The change date for those bounds here is *before* the Hackage upload date so I'm not entirely sure how this happened, but it complicates building with `stack`.

**Comment by ryantrinkle** [comment]
Oops! Just posted a revision to hackage: https://hackage.haskell.org/package/reflex-0.4.0/revisions/

**Comment by ryantrinkle** [comment]
Thanks for pointing this out!
