### ISSUE TITLE
Any migration guide 0.4 -> 0.5?

### ISSUE THREAD

**Issue by qrilka** [reflex-frp/reflex#65]
I was trying to port our app and e.g. stumbled on dissapeared `elWith'` currently. It would be helpful to have some guidelines for the migration.
Thanks

**Comment by ryantrinkle** [comment]
@qrilka `elWith'` is exported [here](https://github.com/reflex-frp/reflex-dom/blob/develop/src/Reflex/Dom/Old.hs#L28); is it possible you're using an older version of reflex-dom?

**Comment by ryantrinkle** [comment]
That being said, a migration guide is a great idea.

**Comment by mightybyte** [comment]
Until we have an actual migration guide, these commits to reflex-dom-contrib updating it for 0.5 provide a decent place to start:

https://github.com/reflex-frp/reflex-dom-contrib/commit/6b12ef4eaa0515a51e960e763ea94e47610db855

https://github.com/reflex-frp/reflex-dom-contrib/commit/785e67aa7c9fac423666501858a1d653895e4953

**Comment by qrilka** [comment]
Ouch, it appears I've posted this issue into wrong project, sorry :)
Actually I've just migrated my code to use `elAttr'`

**Comment by ryantrinkle** [comment]
@qrilka No problem; if you run into more issues, please feel free to post over at reflex-dom's issues.  Closing this for now.
