### ISSUE TITLE
How could I get started on making some extensions for Reflex to use for desktop apps?

### ISSUE THREAD

**Issue by eshansingh** [reflex-frp/reflex#67]
I know that currently your focus is on `reflex-dom`, but just as an experiment to try Reflex out and to have some fun, I've been thinking of making an extension of Reflex that can be used to implement basic desktop stuff using Qt5 or something. What do you think I should start with, first?

**Comment by lynnard** [comment]
You could take a look at reflex-gloss for simple use case, or if you want to build something more complex - see reflex-dom.
