### ISSUE TITLE
Does there exist more than one instance of `Reflex`?

### ISSUE THREAD

**Issue by lspitzner** [reflex-frp/reflex#68]
(or: what is the reasoning for modelling the main interface of this library as a type class?)

**Comment by spl** [comment]
To answer the title question:

1. [`Reflex.Pure`](https://github.com/reflex-frp/reflex/blob/c02df29cd3f56361f34d0d264cf0d672c2d8ecc3/src/Reflex/Pure.hs)
2. [`Reflex.Spider.Internal`](https://github.com/reflex-frp/reflex/blob/fcab3230aed954357e26baec4bce96c629b64704/src/Reflex/Spider/Internal.hs)

**Comment by lspitzner** [comment]
ah i see, Pure was not exposed before.

My intuition suggestions that having a type class is a high cost (typing, errors, documentation) for the benefit, but I really need to make use of reflex first.

Thanks for the quick reply.

**Comment by spl** [comment]
No problem. @ryantrinkle can probably give you a more fulfilling answer to the underlying question.

**Comment by cgibbard** [comment]
There are at least a few others that Ryan has but Spider outperforms them.
The typeclass makes comparative benchmarking easy.

There are also some more interesting applications of that parameter
(timeline transformers) which haven't really been explored. For example one
difference between Reflex and Conal's FRP systems is that the latter had
events which could fire multiple times in a single instant. It may be
possible to have some type function which is applied to the t type
parameter to locally add that when it might be useful. E.g. you'd get
something like:

simultaneously :: Event t [a] -> Event (List t) a
listing :: Event (List t) a -> Event t [a]

(Really not sure about those names though...)
