### ISSUE TITLE
Default instance for Dynamic

### ISSUE THREAD

**Issue by mightybyte** [reflex-frp/reflex#72]
It would be nice to have a Default instance for Dynamic without having to define an orphan.  It would be the simple passthrough instance:

```
instance Default a => Dynamic t a where
    def = constDyn def
```

Is this something you would be open to?  It's not a huge problem, but would be nice to have when calling functions like this one https://github.com/reflex-frp/reflex-dom-semui/blob/master/src/Reflex/Dom/SemanticUI/Button.hs#L172 where you typically will be passing several `constDyn def` parameters.

**Comment by ryantrinkle** [comment]
Yep, sounds good to me!

**Comment by ryantrinkle** [comment]
Closing this in favor of #73.
