### ISSUE TITLE
Don't export `zipDynWith` and refer people to `liftA2` instead?

### ISSUE THREAD

**Issue by mightybyte** [reflex-frp/reflex#82]
Are these equivalent?  If so, this might be worth doing before the new release to decrease the size of the namespace and guide people to the right abstraction.

**Comment by mightybyte** [comment]
Credit for this observation goes to @Fresheyeball

**Comment by mightybyte** [comment]
Never mind...just saw the comment that says `zipDynWith` is more efficient than `liftA2`.  Sorry for the noise.

**Comment by ryantrinkle** [comment]
Eventually, I hope we'll be able to get optimizations to reliably apply to liftA2, such that they're equivalent.  But for now, I think the performance difference warrants the extra use of namespace.
