### ISSUE TITLE
ghcjs base 4.9 support

### ISSUE THREAD

**Issue by lisphacker** [reflex-frp/reflex#84]
Hi

I've installed the current stable haskell platform and built ghcjs. This used v4.9 of the base libraries, which is not supported by reflex. Are there any plans to support this in the near future? 

Cheers 
Gautham

**Comment by ryantrinkle** [comment]
Yes, definitely.  I believe the current version should work fine with 4.9; if you can confirm that, I'll bump it on Hackage.  The github version will have the bound bumped shortly as well.

**Comment by lisphacker** [comment]
Is the stable version built from the master branch or the develop branch? The default seems to be develop.

I tried build the develop branch (default) of reflex with ghcjs (0.2.1-8.0.1). This did not have any problems with base, but had issues with version numbers of the following libs:

haskell-src-exts-1.19.1 (requires >= 1.16 && < 1.18)
haskell-src-meta-0.7.0 (requires 0.6.*)

Would it be safe bumping these up?

**Comment by eskimor** [comment]
If all you need is a working setup, I can recommend reflex-platform with the jsaddle branch - works well for me! But uses a more current reflex/reflex-dom than the one on hackage - so don't rely on hackage docs if you use it!

**Comment by ryantrinkle** [comment]
@lisphacker I'm closing because I think this is obsolete; if I'm missing something, please let me know!
