### ISSUE TITLE
Incremental doc wrong?

### ISSUE THREAD

**Issue by eskimor** [reflex-frp/reflex#87]
Hi there it seems the documentation for Incremental is just copy pasted from Dynamic:

https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/Class.hs#L219

I guess this is wrong?

**Comment by ryantrinkle** [comment]
Well, it's not wrong, but it would be good if it were more descriptive.  A 'Dynamic' is just an 'Incremental' whose patch type always completely replaces the value (rather than doing some potentially-smaller change).

**Comment by eskimor** [comment]
Thank you! That helps a bit! Shall I file a PR with this clarification? That really helped me, so it would definitely be an improvement!

**Comment by ryantrinkle** [comment]
Yes, thanks!

**Comment by eskimor** [comment]
Fixed by PR.
