### ISSUE TITLE
Causality loop found

### ISSUE THREAD

**Issue by eskimor** [reflex-frp/reflex#90]
Hi there!

I just hit the following with my app:

```
Causality loop found
CallStack (from HasCallStack):
  error, called at src/Reflex/Spider/Internal.hs:1609:19 in reflex-0.5.0-CCOIUV1qeMZE5bAytzHgn3:Reflex.Spider.Internal
```

I don't know yet whether this is a bug in reflex or in my application. What things can cause this error? What should I watch out for?

Thank you!

Best regards,

Robert

**Comment by ryantrinkle** [comment]
This means that Reflex has discovered an Event in your application that depends on itself.  E.g.: e' = leftmost [e, e'] would be a simple case.  My general advice is to gradually back out your most recent changes and see when the loop stops.  Once you've figured out *a* place to break the loop, it's usually not too tough to figure out the *right* place to break the loop.

**Comment by eskimor** [comment]
Thank you! Unfortunately this bug is likely quite old, as it only occurs under certain conditions. But anyway now I know what I am looking for.

**Comment by ryantrinkle** [comment]
In that case, it likely means that you have some 'switch' somewhere, and a loop is being creating at runtime by an event being put into that switch dynamically.

I'm not sure whether it's still working, but you can try building Reflex with profiling and with [this flag](https://github.com/reflex-frp/reflex/blob/26eea3636c4ad857e34bd495e71248d915becb91/src/Reflex/Spider/Internal.hs#L68) enabled.  If it works (or even builds at all), it will give you a stack trace for the creation site of every Event that is participating in the cycle.
