### ISSUE TITLE
Causality loop found, cause is weird.

### ISSUE THREAD

**Issue by eskimor** [reflex-frp/reflex#91]
Hi there!

I managed to find the cause of the `causality loop found` error and was also able to fix it, but I don't understand why this fixes anything. I changed the following code:

```haskell
    let
      cFamilyName = fmap (fromMaybe "") . runMaybeT $ do
        cId <- MaybeT $ family'^.selectedFamily
        families' <- MaybeT $ family'^.families
        cFamily  <- MaybeT . pure $ families'^.at cId
        pure $ Gonimo.familyName . Db.familyName $ cFamily
```

to

```haskell
    let
      getFamilyName :: Maybe FamilyId -> Maybe (Map FamilyId Db.Family) -> Text
      getFamilyName Nothing _ = ""
      getFamilyName _ Nothing = ""
      getFamilyName (Just fid) (Just families') = families'^.at fid._Just.to Db.familyName . to Gonimo.familyName

      cFamilyName = zipDynWith getFamilyName (family'^.selectedFamily) (family'^.families)

```

the error disappears/appears reproducible. I am 100% certain that this piece of code causes the bug. I just switched from a monadic solution to zipDynWith. I assume they should be equivalent?

I have a workaround with zipDynWith, so this is not critical, but I would like to understand why the monadic version causes `causality loop found`.

Thanks!

**Comment by ryantrinkle** [comment]
Hmm, I think I need some more context - at least the entire surrounding 'rec' expression.  Feel free to ping me on email, if you don't want to share publicly.

**Comment by eskimor** [comment]
Nop, it's opensource: 
https://github.com/gonimo/gonimo/blob/master/front/src/Gonimo/Client/Family/UI.hs#L60

The bug can be triggered, by triggering `configCreateFamily` events: At some point 'causality loop found' appears, but only if `cFamilyName` got evaluated before (monadic version).

`configCreateFamily` will result in a new family appearing in the map and `selectedFamily` will be updated to point to the newly created family.

**Comment by dfordivam** [comment]
After discussing with @eskimor closing this as it is pretty old and seems to be fixed.
