### ISSUE TITLE
cabal install reflex likely to break ghcjs

### ISSUE THREAD

**Issue by MonsieurCactus** [reflex-frp/reflex#94]
I have gradually installed `ghc 7.10.3` and [`ghcjs`](https://github.com/ghcjs/ghcjs/tree/master) from Github and now I am trying to install `reflex`.  Cabal install reflex gives me the following:

```
$ cabal install reflex

Resolving dependencies...
In order, the following would be installed:
bifunctors-5.3 (latest: 5.4.1) (via: these-0.6.2.1 semigroupoids-5.0.1 profunctors-5.2) (new version)
dependent-sum-0.3.2.2 (latest: 0.4) (via: reflex-0.4.0 dependent-map-0.2.4.0) (new package)
dependent-map-0.2.4.0 (via: reflex-0.4.0) (new package)
exception-transformers-0.4.0.5 (via: reflex-0.4.0) (new package)
haskell-src-exts-1.17.1 (latest: 1.19.1) (via: reflex-0.4.0 haskell-src-meta-0.6.0.14) (new version)
haskell-src-meta-0.6.0.14 (latest: 0.7.0.1) (via: reflex-0.4.0) (new version)
profunctors-5.2 (via: these-0.6.2.1) (reinstall) (changes: bifunctors-5.4.1 -> 5.3)
ref-tf-0.4.0.1 (via: reflex-0.4.0) (new package)
semigroupoids-5.0.1 (latest: 5.1) (via: these-0.6.2.1) (new version)
these-0.6.2.1 (latest: 0.7.3) (via: reflex-0.4.0) (new package)
reflex-0.4.0 (new package)

cabal: The following packages are likely to be broken by the reinstalls:
lens-4.15.1
ghcjs-0.2.0
free-4.12.4
kan-extensions-5.0.1
adjunctions-4.3
Use --force-reinstalls if you want to install anyway.
```

Terminal says I am going to break `lens`, `adjunctions` as well as `ghcjs` itself.  Is there any work-around?

**Comment by ryantrinkle** [comment]
What version of cabal are you using?  You may want to try new-build.

**Comment by MonsieurCactus** [comment]
@ryantrinkle  What new-build are you referring to?

```
$ cabal -V
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library 
```

**Comment by ryantrinkle** [comment]
@MonsieurCactus You need cabal 1.24 or higher, but there is a new build system (invoked as `cabal new-build`), which is meant to deal with this sort of thing more nicely: see http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/

By the way, manually installing is not a very easy way to go with ghcjs.  It's impressive that  you've managed to get this far!  All of my use of ghcjs is via [reflex-platform](https://github.com/reflex-frp/reflex-platform), and I've heard that others have had a good time using stack.  However, I'm not aware of anyone else actually doing it all by hand these days.

**Comment by MonsieurCactus** [comment]
@ryantrinkle installing by hand is failing pretty badly!  I upgraded to Cabal 1.24 and now I can't use it !  Haskell's package managers are quite challenging [[1](http://stackoverflow.com/questions/42321665/cabal-1-24-says-badpackagelocations)]

I think I will leave it to you, sir and just git clone the [reflex platform](https://github.com/reflex-frp/reflex-platform)

**Comment by ryantrinkle** [comment]
@MonsieurCactus Sounds good :)  Let me know how it goes!  By the way, you can always find help in the #reflex-frp chatroom on irc.freenode.net

**Comment by 3noch** [comment]
@MonsieurCactus "Haskell's package managers are quite challenging!" You might find it important to know that you are doing probably one of the hardest tasks possible with Haskell packaging. Most pros don't even tread these waters. :D Most people just stick with `stack`, or in this case reflex-platform.
