### ISSUE TITLE
Build failure on nixpkgs master

### ISSUE THREAD

**Issue by deepfire** [reflex-frp/reflex#97]
The build fails on nixpkgs `master` thusly:
```
desktop@steamos:~/src/reflex-glfw$ nsr /nix/store/csc1glcas5ch21hrbn626l3hbaip8jsi-reflex-0.5.0.drv
these derivations will be built:
  /nix/store/csc1glcas5ch21hrbn626l3hbaip8jsi-reflex-0.5.0.drv
building path(s) ‘/nix/store/ar422r10ydmwl7jzmninl9q790wf1c17-reflex-0.5.0’
setupCompilerEnvironmentPhase
Build with /nix/store/zd8z7wq30fycyz76kmxh46ix6z1r1w7w-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/n9fi7k0i1in9axbl0hil3sr42zklax9l-reflex-0f5b87d14ef4cf048d41657638b5976524c41fa6-src
source root is reflex-0f5b87d14ef4cf048d41657638b5976524c41fa6-src
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-reflex-0.5.0.drv-4/package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-reflex-0.5.0.drv-4/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/ar422r10ydmwl7jzmninl9q790wf1c17-reflex-0.5.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-reflex-0.5.0.drv-4/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/ar422r10ydmwl7jzmninl9q790wf1c17-reflex-0.5.0/lib/ghc-8.0.2/reflex-0.5.0 --ghc-option=-j4 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --ghc-option=-split-sections
Configuring reflex-0.5.0...
Setup: Encountered missing dependencies:
haskell-src-exts >=1.16 && <1.18, haskell-src-meta ==0.6.*
note: keeping build directory ‘/tmp/nix-build-reflex-0.5.0.drv-4’
builder for ‘/nix/store/csc1glcas5ch21hrbn626l3hbaip8jsi-reflex-0.5.0.drv’ failed with exit code 1
error: build of ‘/nix/store/csc1glcas5ch21hrbn626l3hbaip8jsi-reflex-0.5.0.drv’ failed
```

**Comment by deepfire** [comment]
Relaxing the bounds like this:
```
-      haskell-src-exts >= 1.16 && < 1.18,
-      haskell-src-meta == 0.6.*,
+      haskell-src-exts >= 1.16 && < 1.19,
+      haskell-src-meta >= 0.6,
```
brings out the following build failure:
```
[22 of 23] Compiling Reflex.Dynamic.TH ( src/Reflex/Dynamic/TH.hs, dist/build/Reflex/Dynamic/TH.o )

src/Reflex/Dynamic/TH.hs:89:103: error:
    â¢ Could not deduce (Typeable b0) arising from a use of â
      from the context: Data a
        bound by a type expected by the context:
                   Data a => a -> a
        at src/Reflex/Dynamic/TH.hs:89:91-120
      The type variable â is ambiguous
    â¢ In the first argument of â, namely â
      In the second argument of â, namely
        â
      In the second argument of â, namely
        â

src/Reflex/Dynamic/TH.hs:92:13: error:
    â¢ The constructor â should have 2 arguments, but has been given 1
    â¢ In the pattern: Hs.SpliceExp se
      In a case alternative:
          Hs.SpliceExp se
            -> Hs.App
                 (Hs.Var $ Hs.Qual (Hs.ModuleName modName) (Hs.Ident occName))
               $ case se of {
                   Hs.IdSplice v -> Hs.Var $ Hs.UnQual $ Hs.Ident v
                   Hs.ParenSplice ps -> ps }
      In the expression:
        case x of {
          Hs.SpliceExp se
            -> Hs.App
                 (Hs.Var $ Hs.Qual (Hs.ModuleName modName) (Hs.Ident occName))
               $ case se of {
                   Hs.IdSplice v -> Hs.Var $ Hs.UnQual $ Hs.Ident v
                   Hs.ParenSplice ps -> ps }
          _ -> x }
```

**Comment by cgibbard** [comment]
What the heck is going on with those compiler messages? All the relevant
names have been replaced by â.

Maybe something really strange is going on with the text encoding in how
it's constructing the error messages? If not that, then something at least
seems pretty deeply messed up.

On Sun, 19 Mar 2017 at 08:39 Kosyrev Serge <notifications@github.com> wrote:

Relaxing the bounds like this:

-      haskell-src-exts >= 1.16 && < 1.18,
-      haskell-src-meta == 0.6.*,
+      haskell-src-exts >= 1.16 && < 1.19,
+      haskell-src-meta >= 0.6,

brings out the following build failure:

[22 of 23] Compiling Reflex.Dynamic.TH ( src/Reflex/Dynamic/TH.hs,
dist/build/Reflex/Dynamic/TH.o )

src/Reflex/Dynamic/TH.hs:89:103: error:
    â¢ Could not deduce (Typeable b0) arising from a use of â
      from the context: Data a
        bound by a type expected by the context:
                   Data a => a -> a
        at src/Reflex/Dynamic/TH.hs:89:91-120
      The type variable â is ambiguous
    â¢ In the first argument of â, namely â
      In the second argument of â, namely
        â
      In the second argument of â, namely
        â

src/Reflex/Dynamic/TH.hs:92:13: error:
    â¢ The constructor â should have 2 arguments, but has been given 1
    â¢ In the pattern: Hs.SpliceExp se
      In a case alternative:
          Hs.SpliceExp se
            -> Hs.App
                 (Hs.Var $ Hs.Qual (Hs.ModuleName modName) (Hs.Ident occName))
               $ case se of {
                   Hs.IdSplice v -> Hs.Var $ Hs.UnQual $ Hs.Ident v
                   Hs.ParenSplice ps -> ps }
      In the expression:
        case x of {
          Hs.SpliceExp se
            -> Hs.App
                 (Hs.Var $ Hs.Qual (Hs.ModuleName modName) (Hs.Ident occName))
               $ case se of {
                   Hs.IdSplice v -> Hs.Var $ Hs.UnQual $ Hs.Ident v
                   Hs.ParenSplice ps -> ps }
          _ -> x }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/reflex-frp/reflex/issues/97#issuecomment-287613706>,
or mute
the thread

**Comment by deepfire** [comment]
@cgibbard, I guess that's the side-effect of me using the `terminology` terminal emulator.

As it happens, just today I grew tired of its reducing quality and ditched it for `urxvt`..

**Comment by deepfire** [comment]
BTW, a fix is here: https://github.com/reflex-frp/reflex/pull/98

**Comment by ryantrinkle** [comment]
@deepfire Closing this out, as I think it's fixed; if that's not correct, please reopen!  Thanks for the report!
